# Generated by Django 4.2.8 on 2024-04-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='counrty',
            new_name='country',
        ),
    ]
