# Generated by Django 4.2.8 on 2024-04-09 01:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='images',
            field=cloudinary.models.CloudinaryField(default='static/images/placeholder.jpg', max_length=255, verbose_name='product_images'),
        ),
    ]
