# Generated by Django 4.2.8 on 2024-04-09 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_images_productimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
    ]
